image: ubuntu:22.04

definitions:
  steps:
    - step: &npmDev
        name: Build Development Assets
        image: node:18
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - build/**
          - node_modules/**
          - public/**
    - step: &composer
        name: Install composer packages
        image: php:8.1
        script:
          - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev git
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --optimize-autoloader --no-dev
        caches:
          - composer
    - step: &deploy
        name: Deploy React Application to the Development server
        deployment: Staging
        script:
          - apt-get update && apt-get install -y zip git ssh rsync
          - mkdir -p ~/.ssh
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - (umask  077 ; echo $SSH_VARIABLE | base64 --decode > ~/.ssh/id_rsa)
          - bash deploy.sh
          -

pipelines:
  branches:
    develop:
      - parallel:
          - step: *npmDev
          - step: *composer
      - step: *deploy
