image: ubuntu:22.04

definitions:
  steps:
    - step: &npmDev
        name: Build Development Assets
        image: node:20
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm run ag-build
        artifacts:
          - build/**
          - node_modules/**
          - public/**
          - resources/async/**
    - step: &composer
        name: Install composer packages
        image: php:8.2
        script:
          - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev git zip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --optimize-autoloader --ignore-platform-req=ext-gd --ignore-platform-req=ext-imagick --ignore-platform-req=ext-zip --ignore-platform-req=ext-bcmath
        caches:
          - composer
        artifacts:
          - vendor/**
    - step: &deploy
        name: Deploy Application to the Development server
        deployment: Staging
        script:
          - apt-get update && apt-get install -y zip git ssh rsync
          - mkdir -p ~/.ssh
          - ssh-keyscan -t rsa $SERVER_IP > ~/.ssh/known_hosts
          - (umask  077 ; echo $BITBUCKET_SSH_KEY_FILE > ~/.ssh/id_rsa)
          - bash deploy.sh
pipelines:
  branches:
    develop:
      - parallel:
          - step: *npmDev
          - step: *composer
      - step: *deploy
